spring:
  application:
    name: nsuslab-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - jwt.yml
      - logging.yml

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    try-it-out-enabled: true
    display-request-duration: true
    display-operation-id: true
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    default-models-expand-depth: 1
    default-model-expand-depth: 1
  show-actuator: false
  use-management-port: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
  shutdown: graceful

# Management (Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

